# shellcheck shell=sh

SHELLDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"

. "$SHELLDOTDIR/lib.sh" || return 1

# Source profile.d scripts
for f in "$SHELLDOTDIR"/profile.d/*; do
    source_if_exists "$f"
done
unset f

# Add our own utilities last so that they have precedence in the PATH.
PATH_try_prepend "$HOME/.local/bin"

# We don't want the functions from `lib.sh` hanging around unless we're in an
# interactive shell, so we unset them here.
unset -f \
    PATH_try_prepend \
    PATH_try_append \
    has \
    source_if_exists \
    eval_output

# Do not edit this file directly.
# Create a script in $SHELLDOTDIR/profile.d/ instead.
