# shellcheck shell=sh

SHELLDOTDIR=${XDG_CONFIG_HOME:-$HOME/.config}/shell
export SHELLDOTDIR

# shellcheck source=.config/shell/profile
. "$SHELLDOTDIR/profile"

# Do not edit this file directly.
# Use $SHELLDOTDIR/profile instead.
