# shellcheck shell=sh

export SHELLDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
# shellcheck source=.config/shell/profile
. "$SHELLDOTDIR/profile"

# Do not edit this file directly.
# Use $SHELLDOTDIR/profile instead.
