name: Flake Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake check
        shell: bash
        run: nix flake check
